apiVersion: v1
kind: Secret
metadata:
  name: fcg-rabbitmq-secret
type: Opaque
stringData:
  RABBITMQ_DEFAULT_USER: "${RABBITMQ_DEFAULT_USER}"
  RABBITMQ_DEFAULT_PASS: "${RABBITMQ_DEFAULT_PASS}"
  ElasticApm__SecretToken: "${ELASTIC_APM_SECRET_TOKEN}"
