apiVersion: v1
kind: Service
metadata:
  name: fcg-rabbitmq-svc
spec:
  selector:
    app: fcg-rabbitmq
  ports:
    - name: amqp
      port: 5672
      targetPort: 5672
    - name: management
      port: 15672
      targetPort: 15672
  type: LoadBalancer           #Using LoadBalancer to expose the service externally due Azure Limitations