apiVersion: v1
kind: ConfigMap
metadata:
  name: fcg-notification-worker-config
data:
  EmailSettings__SenderEmail: "${EmailSettings__SenderEmail}"
  RabbitMQ__HostName: "${RabbitMQ__HostName}"
  RabbitMQ__QueueName: "${RabbitMQ__QueueName}"
  ASPNETCORE_ENVIRONMENT: "${ASPNETCORE_ENVIRONMENT}"
  DOTNET_ENVIRONMENT: "${DOTNET_ENVIRONMENT}"