apiVersion: v1
kind: ConfigMap
metadata:
  name: fcg-notification-worker-config
data:
  EmailSettings__SenderEmail: "${EmailSettings__SenderEmail}"
  RabbitMQ__HostName: "${RabbitMQ__HostName}"
  RabbitMQ__QueueName: "${RabbitMQ__QueueName}"
  ElasticApm__Enabled: "${ELASTIC_APM_ENABLED}"
  ElasticApm__ServerUrl: "${ELASTIC_APM_SERVER_URL}"
  ElasticApm__ServiceName: "${APM_SERVICE_NAME}"
  ElasticApm__Environment: "${ENV}"
  ASPNETCORE_ENVIRONMENT: "${ENV}"
  DOTNET_ENVIRONMENT: "${ENV}"