apiVersion: v1
kind: Secret
metadata:
  name: fcg-notification-worker-secret
type: Opaque
stringData:
  EmailSettings__ConnectionString: "${EmailSettings__ConnectionString}"
  RabbitMQ__UserName: "${RabbitMQ__UserName}"
  RabbitMQ__Password: "${RabbitMQ__Password}"